<?php
if (!defined('REMEMBER_ME')) define('REMEMBER_ME', 1);
if (!defined('FB')) define('FB', 'FACEBOOK');
if (!defined('NO_PAGE')) define('NO_PAGE', 0);
if (!defined('HAVE_PAGE')) define('HAVE_PAGE', 1);
if (!defined('LIMIT')) define('LIMIT', 10);
if (!defined('LIMIT_COMMENT_OVERVIEW')) define('LIMIT_COMMENT_OVERVIEW', 2);
if (!defined('LIMIT_COMMENT')) define('LIMIT_COMMENT', 10);

if (!defined('NOTIFICATION_USER_COMMENT_POST')) define('NOTIFICATION_USER_COMMENT_POST', 'NOTIFICATION_USER_COMMENT_POST');
if (!defined('NOTIFICATION_USER_REACT_POST')) define('NOTIFICATION_USER_REACT_POST', 'NOTIFICATION_USER_REACT_POST');
if (!defined('NOTIFICATION_USER_REPLY_COMMENT')) define('NOTIFICATION_USER_REPLY_COMMENT', 'NOTIFICATION_USER_REPLY_COMMENT');

if (!defined('NOTIFICATION_UNREAD')) define('NOTIFICATION_UNREAD', 0);

if (!defined('ACCOUNT_ACTIVE')) define('ACCOUNT_ACTIVE', 1);
if (!defined('ACCOUNT_UNACTIVE')) define('ACCOUNT_UNACTIVE', 0);
if (!defined('LIMIT_REGISTER_QUERY')) define('LIMIT_REGISTER_QUERY', 3);

if (!defined('SCHOOLE_HIGHSCHOOL')) define('SCHOOLE_HIGHSCHOOL', 'SCHOOLE_HIGHSCHOOL');
if (!defined('SCHOOLE_UNIVERSITY')) define('SCHOOLE_UNIVERSITY', 'SCHOOLE_UNIVERSITY');